version: 0.2

env:
  variables:
    NODE_OPTIONS: --max-old-space-size=7168
    CI: true
  secrets-manager:
     GATSBY_STORYBLOK_SPACE_API_KEY: $WEBSITE_NAME-secret:$WEBSITE_NAME.apikeys.$ENVIRONMENT

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - export GATSBY_STORYBLOK_SPACE_API_KEY_NAME="${WEBSITE_NAME}:${ENVIRONMENT}"
      - export GATSBY_AWS_S3_BUCKET=${WEBSITE_BUCKET}
      - export GATSBY_ENV=${ENVIRONMENT}
      - export GATSBY_WEBSITE_NAME=${WEBSITE_NAME}
      - export GATSBY_WEBSITE_URL="https://${WEBSITE_DOMAIN}"
      - 'npm ci --cache .npm --prefer-offline --no-audit'
  build:
    commands:
      - 'npm run build'
      - printenv
  post_build:
    commands:
      - npm run deploy
artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)
  base-directory: public
cache:
  paths:
    - '.npm'