# ### Github Secrets
#
# - `ROCHE_AWS_ACCESS_KEY_ID` -  - AWS Access Key ID.
# - `ROCHE_AWS_SECRET_ACCESS_KEY` - AWS Secret Access Key.
# - `ROCHE_AWS_DEFAULT_REGION` - AWS Default Region.
# - `PREVIEW_STATIC_WEB_SITE_BUCKET` - Static Web Site URL (S3 Bucket).
# - `PREVIEW_STORYBLOK_SPACE_API_KEY` - Storyblok Space API Key with preview access.
# - `PREVIEW_ROCHE_COMPONENTS_LIBRARY_URL` - URL of the Roche Component Library.
# - `PREVIEW_CLOUDFRONT_DISTRIBUTION_ID` - Cloudfront distribution ID.

name: Preview

on:
  push:
    branches:
      - master

  # New preview website should be rebuild and deployed everytime components or content changes
  repository_dispatch:
    types: [ storyblok_components_changed, storyblok_content_changed ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ROCHE_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ROCHE_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}
  AWS_REGION: ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET: ${{ secrets.PREVIEW_STATIC_WEB_SITE_BUCKET }}
  DISTRIBUTION: ${{ secrets.PREVIEW_CLOUDFRONT_DISTRIBUTION_ID }}
  GATSBY_STORYBLOK_SPACE_API_KEY: ${{ secrets.PREVIEW_STORYBLOK_SPACE_API_KEY }}
  GATSBY_ROCHE_COMPONENTS_LIBRARY_URL: ${{ secrets.PREVIEW_ROCHE_COMPONENTS_LIBRARY_URL }}

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm run test || true # Tests not blocking for while

      - name: Generate Audit report
        run: npm audit || true # Audit not blocking for while

      - name: Build the website
        run: npm run build

      - name: Deploy preview (public)
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: "public"

      - name: Invalidate Distribution
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/index.html /editor /editor/index.html'
