name: PreviewStaging # IMPORTANT!!! This name MUST not be changed !!!! It is used to check for running workflows.

on:
  push:
    branches:
      - staging

  repository_dispatch:
    types:
     - preview_staging_website_deploy_requested
     - live_staging_website_deploy_requested # Preview is also deployed because Storyblok allows publishing without calling the deploy preview task

env:
  AWS_S3_BUCKET: ${{ secrets.PREVIEW_STAGING_AWS_S3_BUCKET }}
  DISTRIBUTION: ${{ secrets.PREVIEW_STAGING_DISTRIBUTION }} 
  GATSBY_GOOGLE_RECAPTCHA_KEY: ${{ secrets.ROCHE_GOOGLE_RECAPTCHA_SITE_KEY }}
  GATSBY_ROCHE_COMPONENTS_LIBRARY_URL: ${{ secrets.STAGING_ROCHE_COMPONENTS_LIBRARY_URL }}
  STORYBLOK_API_KEY_NAME: ${{ secrets.PREVIEW_STORYBLOK_API_KEY_NAME }}
  STORYBLOK_SPACE_ID: ${{ secrets.STAGING_STORYBLOK_SPACE_ID }}
  STORYBLOK_SPACE_NAME: ${{ secrets.STAGING_STORYBLOK_SPACE_NAME }}
  WEBHOOKS_API_URL: ${{ secrets.ROCHE_WEBHOOKS_API_URL }}
  GATSBY_BRIGHTCOVE_ACCOUNT_ID: ${{ secrets.ROCHE_BRIGHTCOVE_ACCOUNT_ID }}
  GATSBY_BRIGHTCOVE_PLAYER_ID: ${{ secrets.ROCHE_BRIGHTCOVE_PLAYER_ID }}
  GATSBY_WEBSITE_URL: ${{ secrets.PREVIEW_STAGING_WEBSITE_URL }}

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm run test || true # Tests not blocking for while

      - name: Generate Audit report
        run: npm audit || true # Audit not blocking for while

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROCHE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ROCHE_AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}

      - name: Set GATSBY_STORYBLOK_SPACE_API_KEY
        run: . ./scripts/set-gatsby-storyblok-space-api-key.sh

      - name: Set GATSBY_STORYBLOK_SPACE_API_KEY_NAME
        run: . ./scripts/set-gatsby-storyblok-space-api-key-name.sh

      - name: Set COGNITO_USERPOOL_ID (Depends on STORYBLOK_SPACE_NAME)
        run: . ./scripts/set-cognito-user-pool.sh

      - name: Set COGNITO_USERPOOL_CLIENT_ID (Depends on STORYBLOK_SPACE_NAME and COGNITO_USERPOOL_ID)
        run: . ./scripts/set-cognito-user-pool-client.sh

      - name: Emit event preview_deploy_started
        run: . ./scripts/emit-event-preview-deploy-started.sh

      - name: Build the website
        run: npm run build
        env:
          CI: true
          GATSBY_ENV: preview
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: false
          NODE_OPTIONS: --max-old-space-size=7168

      - name: Deploy preview (public)
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: "public"

      - name: Emit event preview_deploy_finished
        run: . ./scripts/emit-event-preview-deploy-finished.sh

      - name: Repository Dispatch update_lambda_config_requested
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ROCHE_GITHUB_ACCESS_TOKEN }}
          event-type: update_lambda_config_requested
          client-payload: '{"websiteName": "${{env.STORYBLOK_SPACE_NAME}}", "apiKeyName": "preview", "environment": "preview"}'

      - name: Invalidate Distribution
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: '/*'
