name: Check

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"

env:
  STORYBLOK_SPACE_NAME: 'roche-website-starter'
  STORYBLOK_API_KEY_NAME: 'preview'
  GATSBY_ROCHE_COMPONENTS_LIBRARY_URL: ${{ secrets.ROCHE_COMPONENTS_LIBRARY_URL }}
  GATSBY_GOOGLE_RECAPTCHA_KEY: ${{ secrets.ROCHE_GOOGLE_RECAPTCHA_SITE_KEY }}

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install packages
        run: npm ci

      - name: Run Lint verification
        run: npm run lint

      - name: Run Tests
        run: npm run test || true # Tests not blocking for while

      - name: Generate Audit report
        run: npm audit || true # Audit not blocking for while

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ROCHE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ROCHE_AWS_SECRET_ACCESS_KEY }}
          aws-region:  ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}

      - name: Set GATSBY_STORYBLOK_SPACE_API_KEY
        run: . ./scripts/set-gatsby-storyblok-space-api-key.sh

      - name: Set GATSBY_STORYBLOK_SPACE_API_KEY_NAME
        run: . ./scripts/set-gatsby-storyblok-space-api-key-name.sh

      - name: Set COGNITO_USERPOOL_ID (Depends on STORYBLOK_SPACE_NAME)
        run: . ./scripts/set-cognito-user-pool.sh

      - name: Set COGNITO_USERPOOL_CLIENT_ID (Depends on STORYBLOK_SPACE_NAME and COGNITO_USERPOOL_ID)
        run: . ./scripts/set-cognito-user-pool-client.sh

      - name: Build the website
        run: npm run build
