name: Check

on:
  push:
    branches:
      - "*"
      - "*/*"
      - "**"
      - "!master"

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Install packages
        run: npm ci

      - name: Run Lint verification
        run: npm run lint

      - name: Run Tests
        run: npm run test || true # Tests not blocking for while

      - name: Generate Audit report
        run: npm audit || true # Audit not blocking for while

      - name: Build the website
        run: npm run build
        env:
          CI: true
          GATSBY_ENV: live
          NODE_OPTIONS: --max-old-space-size=7168
