# name: RefreshCaches

# on:
#   schedule:
#     - cron: 0 0 */1 * * # Every day at midnight
  
# jobs:
#   request_cache_refresh:
#     name: Request Cache Refresh
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Call repository dispatch event to refresh the Check cache
#         run: echo 'Call repository dispatch to trigger the Check workflow with refresh_cache_requested'