# ### Github Secrets
#
# - `ROCHE_AWS_ACCESS_KEY_ID` - AWS Access Key ID.
# - `ROCHE_AWS_SECRET_ACCESS_KEY` - AWS Secret Access Key.
# - `ROCHE_AWS_DEFAULT_REGION` - AWS Default Region.
# - `LIVE_STATIC_WEB_SITE_BUCKET` - Static Web Site URL (S3 Bucket).
# - `LIVE_STORYBLOK_SPACE_API_KEY` - Storyblok Space API Key with public access.
# - `LIVE_ROCHE_COMPONENTS_LIBRARY_URL` - URL of the Roche Component Library.

name: Release

on:
  push:
    branches:
      - master
  
  # New live website should be rebuild and deployed everytime content changes
  repository_dispatch:
    types: [ storyblok_content_changed ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.ROCHE_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.ROCHE_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}
  AWS_REGION: ${{ secrets.ROCHE_AWS_DEFAULT_REGION }}
  AWS_S3_BUCKET: ${{ secrets.LIVE_STATIC_WEB_SITE_BUCKET }}
  GATSBY_STORYBLOK_SPACE_API_KEY: ${{ secrets.LIVE_STORYBLOK_SPACE_API_KEY }}
  GATSBY_ROCHE_COMPONENTS_LIBRARY_URL: ${{ secrets.LIVE_ROCHE_COMPONENTS_LIBRARY_URL }}

jobs:
  pre_release:
    name: Check if a release with the same version number already exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.0.0
        id: package-version

      - name: Print current version from package.json
        run: echo "${{ steps.package-version.outputs.current-version }}"

      - name: Check if tag already exists
        id: tag_existance
        run: echo "##[set-output name=oldtag;]$(echo $(git tag -l "${{ steps.package-version.outputs.current-version }}"))"

      - name: Validate tag reference from github
        if: ${{ steps.tag_existance.outputs.oldtag != '' }}
        run: exit 1

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: pre_release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install packages
        run: npm ci

      - name: Run Tests
        run: npm run test || true # Tests will pass for while

      - name: Generate Audit report
        run: npm audit || true # Audit will pass for while

      - name: Build App
        run: npm run build:public

      - name: Get current package version
        uses: martinbeentjes/npm-get-version-action@v1.0.0
        id: package-version

      - name: Print current version from package.json
        run: echo "${{ steps.package-version.outputs.current-version }}"

      - name: Deploy the release version
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: "public"
          DEST_DIR: "releases/${{ steps.package-version.outputs.current-version }}"

      - name: Deploy the release as latest version
        uses: jakejarvis/s3-sync-action@v0.5.1
        env:
          SOURCE_DIR: "public"

      - uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          CUSTOM_TAG: ${{ steps.package-version.outputs.current-version }}
          RELEASE_BRANCHES: master
